# Path to your oh-my-zsh configuration.
ZSH=$HOME/.oh-my-zsh

# Set name of the theme to load.
# Look in ~/.oh-my-zsh/themes/
# Optionally, if you set this to "random", it'll load a random theme each
# time that oh-my-zsh is loaded.
ZSH_THEME="robbyrussell"

# Example aliases
# alias zshconfig="mate ~/.zshrc"
# alias ohmyzsh="mate ~/.oh-my-zsh"

# Set to this to use case-sensitive completion
# CASE_SENSITIVE="true"

# Comment this out to disable bi-weekly auto-update checks
# DISABLE_AUTO_UPDATE="true"

# Uncomment to change how often before auto-updates occur? (in days)
# export UPDATE_ZSH_DAYS=13

# Uncomment following line if you want to disable colors in ls
# DISABLE_LS_COLORS="true"

# Uncomment following line if you want to disable autosetting terminal title.
# DISABLE_AUTO_TITLE="true"

# Uncomment following line if you want to disable command autocorrection
# DISABLE_CORRECTION="true"

# Uncomment following line if you want red dots to be displayed while waiting for completion
# COMPLETION_WAITING_DOTS="true"

# Uncomment following line if you want to disable marking untracked files under
# VCS as dirty. This makes repository status check for large repositories much,
# much faster.
# DISABLE_UNTRACKED_FILES_DIRTY="true"

# Which plugins would you like to load? (plugins can be found in ~/.oh-my-zsh/plugins/*)
# Custom plugins may be added to ~/.oh-my-zsh/custom/plugins/
# Example format: plugins=(rails git textmate ruby lighthouse)
plugins=(git fbterm)

if [[ -z "$LANG" ]]; then
  export LANG=zh_CN.UTF-8
fi

fbterm() {
  bg_file_list=(
    /var/.config/wallpaper.jpg
    /usr/share/backgrounds/xfce/xfce-blue.jpg
    /usr/share/backgrounds/xfce/xfce-evil.jpg
    /usr/share/archlinux/wallpaper/archlinux-simplyblack.png
  )
  maybe_bg_list=()
  for i in "${bg_file_list[@]}"
  do
    if [[ -f "$i" ]]
    then
        maybe_bg_list+=("$i")
    fi
  done

  bg_file_index=$(( ( RANDOM % ${#maybe_bg_list[@]} ) + 1 ))
  bg_file=${maybe_bg_list[$bg_file_index]}
  echo -ne "\e[?25l"
  fbv -ciuker "$bg_file" << EOF
q
EOF
  export FBTERM_BACKGROUND_IMAGE=1
  fcitx-fbterm-helper -l > /dev/null
}

source $ZSH/oh-my-zsh.sh

# Customize to your needs...
export PATH=$PATH:/usr/local/sbin:/usr/local/bin:/usr/bin
